### ISSUE TITLE
Exceptions silently fail during post-processing

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#5315]
## Bug Description

When a sanitizer or Optimizer transformer fails, the response for an AMP page can still have a 200 status code but the page won't be AMP. 

Consider the following plugin code being active:

```php
add_filter(
	'amp_schemaorg_metadata',
	function () {
		throw new Exception( 'FAIL!' );
	}
);
```

When in Transitional mode, accessing an AMP page will show AMP in the admin bar, but the page is not AMP. This is because the post-processor was unable to process the buffer to add the `amp` attribute to the `html` page.

This was recently [reported](https://wordpress.org/support/topic/error-1407/#post-13340160) on the support forum for a site which had the following in the error log:

```
PHP Fatal error: Uncaught Error: Call to a member function format() on bool in …/wp-content/themes/wordpress-starter-template/functions.php:925
Stack trace:
#0 …/wp-includes/class-wp-hook.php(287): nl_amp_set_schema_type(Array, Object(WP_Post))
#1 …/wp-includes/plugin.php(206): WP_Hook->apply_filters(Array, Array)
#2 …/wp-content/plugins/amp/includes/amp-helper-functions.php(1794): apply_filters('amp_post_templa...', Array, Object(WP_Post))
#3 …/wp-content/plugins/amp/src/Transformer/AmpSchemaOrgMetadataConfiguration.php(41): amp_get_schemaorg_metadata()
#4 …/wp-content/plugins/amp/vendor/ampproject/optimizer/src/Configuration/BaseTransformerConfiguration.php(34): AmpProject\\AmpWP\\Transformer\\AmpSchemaOrgMetadataConfiguration->getAllowedKeys()
#5 …/wp-content/plugins/amp/vendor/ampproject/optimizer/src/Configuration.php(191): in …/wp-content/themes/wordpress-starter-template/functions.php on line 925
```

In spite of the fatal error, the page returned with 200 OK. This is confusing and is likely the source of many reports from users who have reported GSC complaining about the `amphtml` links not pointing to AMP pages.

## Expected Behaviour

When a fatal error occurs during post-processing, the response should be 500 Internal Server Error, and the buffered output should be replaced with `wp_die()`-styled error screen explaining that there was an error during AMP processing. If `WP_DEBUG_DISPLAY` is enabled, the error details can be displayed on this screen.

Note that #3158 includes a more expansive discussion about how to handle error logging and bug reporting. It should still be moved forward, but we can implement a quick win to help users identify AMP generation problems with a try/catch block.

## Steps to reproduce

1. Add the above `amp_schemaorg_metadata` filter code to a custom plugin or a theme's `functions.php`.
2. Enable Transitional mode.
3. Access an AMP page.
4. Note the page silently fails.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* A fatal error should result in an error page being served.
* When `WP_DEBUG_DISPLAY` is enabled, the properties of the caught `Exception` should be printed.
* The error details should also be forwarded along to the PHP error log via `error_log()`.

## Implementation brief

```diff
--- a/includes/class-amp-theme-support.php
+++ b/includes/class-amp-theme-support.php
@@ -1834,7 +1834,14 @@ class AMP_Theme_Support {
 	 */
 	public static function finish_output_buffering( $response ) {
 		self::$is_output_buffering = false;
-		$response                  = self::prepare_response( $response );
+
+		try {
+			$response = self::prepare_response( $response );
+		} catch ( Exception $e ) {
+			// @todo Return a wp_die()-styled screen and send a 500 status code. Show $e details if WP_DEBUG_DISPLAY is enabled and send $e to error log.
+		}
+
 
 		/**
 		 * Fires when server timings should be sent.
```

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment]
QA Passed

Given this plugin:

```php
<?php
/**
 * Plugin Name: AMP Throw Error While Filtering Schema Metadata
 */

function throw_my_exception() {
	throw new Exception( 'FAIL!' );
}

add_filter(
	'amp_schemaorg_metadata',
	'throw_my_exception'
);
```

When `WP_DEBUG_DISPLAY` is enabled:

Before | After
-------|------
![image](https://user-images.githubusercontent.com/134745/92161688-cc5a8700-ede5-11ea-8e5e-82e2c09d5eea.png) | ![image](https://user-images.githubusercontent.com/134745/92161723-d8dedf80-ede5-11ea-8ce4-4cbf314613cf.png)

When `WP_DEBUG_DISPLAY` is disabled:

Before | After
-------|------
![image](https://user-images.githubusercontent.com/134745/92161818-0461ca00-ede6-11ea-8dae-4a00b39c1b7d.png) | ![image](https://user-images.githubusercontent.com/134745/92161848-10e62280-ede6-11ea-9867-b6bc924e7c17.png)
